spring.application.name=ms-farmaexpress-bff
server.port=${SERVER_PORT:8080}
services.prescriptions.url=${PRESCRIPTIONS_URL}
services.catalog.url=${CATALOG_URL}
services.connect-timeout=${HTTP_CONNECT_TIMEOUT:3s}
services.read-timeout=${HTTP_READ_TIMEOUT:10s}
frontend.origin=${FRONTEND_ORIGIN}
spring.mvc.problemdetails.enabled=true
